project:
  type: website

website:
  title: "Tequila Tutorials"
  description: "quantum computing, quantum chemistry and tequila"
  image: tequila_logo.png
  repo-url: https://github.com/tequilahub/tequila
  repo-actions: [source, issue]
  navbar:
    logo: tequila_logo.png
    right:
      - text: "Research"
        file: research.qmd
      - text: "Tutorials"
        file: tutorials.qmd
      - text: "FAQ"
        file: FAQ/FAQ.ipynb
      - text: "Contribution"
        file: Contribution/Contribution.ipynb

  favicon: favicon.ico
  open-graph: true
  google-analytics: G-V7DRP5E70N
  cookie-consent:
      type: express
      style: simple 

format:
  html:
    theme:
      light: [flatly, theme-light.scss]
      dark: [darkly, theme-dark.scss]
    css: styles.css

execute:
  freeze: auto


