name: BlogQA
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - psi4
  - pip
  - texlive
  - pip:
      - tequila-basic
      - pyyaml
      - nbformat
      - nbclient
      - numpy
      - scipy
      - matplotlib
      - qulacs
      - pyscf
      
